name: Build on push
on:
  push:
    branches-ignore:
      - 'release'

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/catthehacker/ubuntu:pwsh-latest
    defaults:
      run:
        shell: pwsh
    
    steps:
      - name: setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: restore
        run: dotnet restore
      
      - name: build
        run: dotnet build
      
      - name: pack
        run: dotnet pack

      - name: upload artifact to github
        if: ${{ github.server_url == 'https://github.com' }} # only run on github
        uses: actions/upload-artifact@v4
        with:
          path: ./nupkg/*.nupkg